# Global configuration
global:
  namespace: elk
  elasticVersion: "9.1.3"
  filebeatVersion: "8.18.6"
  
# Certificate configuration
certificates:
  enabled: true
  caValidityDays: 3650
  certValidityDays: 3650
  
# Elasticsearch configuration
elasticsearch:
  enabled: true
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: "9.1.3"
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  auth:
    elasticPassword: "elasticpassword"
  
  ssl:
    enabled: true
    
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  
  env:
    esJavaOpts: "-Xms512m -Xmx1024m"
  
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: ""
  
  service:
    type: ClusterIP
    httpPort: 9200
    transportPort: 9300

# Kibana configuration
kibana:
  enabled: true
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: "9.1.3"
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  auth:
    kibanaPassword: "kibanapassword"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  service:
    type: NodePort
    port: 5601
    nodePort: 30601
  
  encryptionKey: "BqqvcUssLZUf1brzp2uaEVoiN7ej5tWg"

# Logstash configuration
logstash:
  enabled: true
  image:
    repository: logstash
    tag: "9.1.2"
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  env:
    lsJavaOpts: "-Xms512m -Xmx512m"
  
  service:
    type: ClusterIP
    port: 5044

# Filebeat configuration
filebeat:
  enabled: true
  image:
    repository: docker.elastic.co/beats/filebeat
    tag: "8.18.6"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

# APM Server configuration
apmServer:
  enabled: true
  image:
    repository: docker.elastic.co/apm/apm-server
    tag: "9.1.3"
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  
  service:
    type: NodePort
    port: 8200
    nodePort: 30602

# Demo Application configuration
demoApp:
  enabled: true
  image:
    repository: node
    tag: "18-alpine"
    pullPolicy: IfNotPresent
  
  replicas: 1
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  service:
    type: NodePort
    port: 3000
    nodePort: 30600