# Development values for ELK Stack
global:
  namespace: elk-dev

elasticsearch:
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

kibana:
  service:
    type: NodePort
    nodePort: 30601

logstash:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

demoApp:
  enabled: true