# Production values for ELK Stack
global:
  namespace: elk-prod
  elasticVersion: "9.1.3"

elasticsearch:
  replicas: 3
  persistence:
    enabled: true
    size: 100Gi
    storageClassName: "fast-ssd"
  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
      cpu: "4000m"
  auth:
    elasticPassword: "your-secure-password-here"

kibana:
  replicas: 2
  service:
    type: LoadBalancer
  auth:
    kibanaPassword: "your-secure-kibana-password"

logstash:
  replicas: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

apmServer:
  replicas: 2
  service:
    type: LoadBalancer

demoApp:
  enabled: false  # Disable in production