{{- if .Values.apmServer.enabled }}
# APM Server ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk-stack.fullname" . }}-apm-server-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:{{ .Values.apmServer.service.port }}"
      rum:
        enabled: true
        allow_origins: ['*']
      ssl:
        enabled: false

    output.elasticsearch:
      {{- if .Values.elasticsearch.ssl.enabled }}
      hosts: ["https://{{ include "elk-stack.fullname" . }}-elasticsearch:{{ .Values.elasticsearch.service.httpPort }}"]
      {{- else }}
      hosts: [""http://{{ include "elk-stack.fullname" . }}-elasticsearch:{{ .Values.elasticsearch.service.httpPort }}"]
      {{- end }}
      username: "elastic"
      password: {{ .Values.elasticsearch.auth.elasticPassword | quote }}
      {{- if .Values.elasticsearch.ssl.enabled }}
      ssl:
        certificate_authorities: ["/usr/share/apm-server/config/certs/ca.crt"]
        verification_mode: "certificate"
      {{- end }}

    setup.template.settings:
      index.number_of_shards: 1
      index.codec: best_compression

    setup.kibana:
      {{- if .Values.elasticsearch.ssl.enabled }}
      host: "https://{{ include "elk-stack.fullname" . }}-kibana.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.kibana.service.port }}"
      {{- else }}
      host: "http://{{ include "elk-stack.fullname" . }}-kibana.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.kibana.service.port }}"
      {{- end }}

    logging:
      level: info
      to_files: true
      files:
        path: /var/log/apm-server
        name: apm-server.log
        keepfiles: 7
        permissions: 0644

    monitoring:
      enabled: false
---
# APM Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elk-stack.fullname" . }}-apm-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: apm-server
spec:
  replicas: {{ .Values.apmServer.replicas }}
  selector:
    matchLabels:
      {{- include "elk-stack.apmserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elk-stack.apmserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: apm-server
        image: {{ .Values.apmServer.image.repository }}:{{ .Values.apmServer.image.tag }}
        imagePullPolicy: {{ .Values.apmServer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.apmServer.service.port }}
          name: http
        volumeMounts:
        - name: apm-server-config
          mountPath: /usr/share/apm-server/apm-server.yml
          subPath: apm-server.yml
        {{- if .Values.elasticsearch.ssl.enabled }}
        - name: elasticsearch-certs
          mountPath: /usr/share/apm-server/config/certs
          readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.apmServer.resources | nindent 10 }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.apmServer.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.apmServer.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: apm-server-config
        configMap:
          name: {{ include "elk-stack.fullname" . }}-apm-server-config
      {{- if .Values.elasticsearch.ssl.enabled }}
      - name: elasticsearch-certs
        secret:
          secretName: {{ include "elk-stack.fullname" . }}-certs
      {{- end }}
---
# APM Server Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elk-stack.fullname" . }}-apm-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: apm-server
spec:
  selector:
    {{- include "elk-stack.apmserver.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.apmServer.service.port }}
      targetPort: {{ .Values.apmServer.service.port }}
      {{- if eq .Values.apmServer.service.type "NodePort" }}
      nodePort: {{ .Values.apmServer.service.nodePort }}
      {{- end }}
  type: {{ .Values.apmServer.service.type }}
