{{- if .Values.filebeat.enabled }}
# Filebeat ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk-stack.fullname" . }}-filebeat-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        enabled: true
        paths:
          - /var/log/containers/*.log
        multiline.pattern: '^[[:space:]]'
        multiline.negate: false
        multiline.match: after
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
          - drop_fields:
              fields: ["agent", "ecs", "host"]

    filebeat.autodiscover:
      providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          unique: true
          templates:
            - config:
                - type: container
                  paths:
                    - /var/log/containers/*${data.kubernetes.container.id}.log
              processors:
                - add_kubernetes_metadata:
                    matchers:
                    - logs_path:
                        logs_path: "/var/log/containers/"

    processors:
      - add_cloud_metadata:
          timeout: 3s
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~

    output.logstash:
      hosts: ["{{ .Values.logstash.service.name }}:{{ .Values.logstash.service.port }}"]

    setup.template.enabled: false
    setup.ilm.enabled: false
    monitoring.enabled: false

    logging.level: info
    logging.to_files: true
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644
---
# Filebeat ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elk-stack.filebeat.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
---
# Filebeat ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elk-stack.filebeat.serviceAccountName" . }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
      - nodes
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch"]
---
# Filebeat ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elk-stack.filebeat.serviceAccountName" . }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "elk-stack.filebeat.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "elk-stack.filebeat.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
# Filebeat DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "elk-stack.fullname" . }}-filebeat
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
spec:
  selector:
    matchLabels:
      {{- include "elk-stack.filebeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elk-stack.filebeat.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "elk-stack.filebeat.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: {{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}
        imagePullPolicy: {{ .Values.filebeat.image.pullPolicy }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e"
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        resources:
          {{- toYaml .Values.filebeat.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: {{ include "elk-stack.fullname" . }}-filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
{{- end }}