{{- if .Values.logstash.enabled }}
# Logstash Pipeline ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elk-stack.fullname" . }}-logstash-pipeline
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
    pipeline.workers: 1
    pipeline.batch.size: 125
    pipeline.batch.delay: 50

  pipeline.conf: |
    input {
      beats {
        port => {{ .Values.logstash.service.port }}
        host => "0.0.0.0"
      }
    }

    filter {
      if [fields][log_type] == "apache" {
        grok {
          match => { "message" => "%{COMBINEDAPACHELOG}" }
        }
      }
      
      if [kubernetes] {
        mutate {
          add_field => { 
            "k8s_namespace" => "%{[kubernetes][namespace]}"
            "k8s_pod" => "%{[kubernetes][pod][name]}"
            "k8s_container" => "%{[kubernetes][container][name]}"
          }
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        user => "${ELASTICSEARCH_USER}"
        password => "${ELASTICSEARCH_PASSWORD}"
        ssl_enabled => ${ELASTICSEARCH_SSL_ENABLED}
        ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca.crt"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
---
# Logstash Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elk-stack.fullname" . }}-logstash
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: logstash
spec:
  replicas: {{ .Values.logstash.replicas }}
  selector:
    matchLabels:
      {{- include "elk-stack.logstash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elk-stack.logstash.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: logstash
        image: {{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}
        imagePullPolicy: {{ .Values.logstash.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.logstash.service.port }}
          name: beats
          protocol: TCP
        env:
        - name: LS_JAVA_OPTS
          value: {{ .Values.logstash.env.lsJavaOpts | quote }}
        - name: ELASTICSEARCH_HOST
          value: {{ .Values.elasticsearch.service.name | quote }}
        - name: ELASTICSEARCH_PORT
          value: {{ .Values.elasticsearch.service.httpPort | quote }}
        - name: ELASTICSEARCH_USER
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "elk-stack.fullname" . }}-elasticsearch-secrets
              key: password
        - name: ELASTICSEARCH_SSL_ENABLED
          value: {{ .Values.elasticsearch.ssl.enabled | quote }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config
        - name: pipeline-config
          mountPath: /usr/share/logstash/pipeline
        {{- if .Values.elasticsearch.ssl.enabled }}
        - name: certs
          mountPath: /usr/share/logstash/config/certs
          readOnly: true
        {{- end }}
        resources:
          {{- toYaml .Values.logstash.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: beats
          initialDelaySeconds: 60
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: beats
          initialDelaySeconds: 120
          periodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: {{ include "elk-stack.fullname" . }}-logstash-pipeline
      - name: pipeline-config
        configMap:
          name: {{ include "elk-stack.fullname" . }}-logstash-pipeline
      {{- if .Values.elasticsearch.ssl.enabled }}
      - name: certs
        secret:
          secretName: {{ include "elk-stack.fullname" . }}-certs
      {{- end }}
---
# Logstash Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logstash.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "elk-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: logstash
spec:
  selector:
    {{- include "elk-stack.logstash.selectorLabels" . | nindent 4 }}
  ports:
    - name: beats
      protocol: TCP
      port: {{ .Values.logstash.service.port }}
      targetPort: beats
  type: {{ .Values.logstash.service.type }}
{{- end }}